# Join Statements

## Introduction

In this lab, you'll practice your knowledge on Join statements.

## Objectives

You will be able to:
- Write queries that make use of various types of Joins
- Join tables using foreign keys

## CRM Schema

In almost all cases, rather then just working with a single table we will typically need data from multiple tables. 
Doing this requires the use of **joins ** using shared columns from the two tables. 

In this lab, we'll use the same Customer Relationship Management (CRM) database we used in our lecture before!
<img src='Database-Schema.png' width=550>

## Connecting to the Database
Import the necessary packages and connect to the database **data.sqlite**.

In [2]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('data.sqlite', detect_types=sqlite3.PARSE_COLNAMES)
cur = conn.cursor()

## Display the names of all the employees in Boston.

In [3]:
cur.execute("""select firstName, lastName , city from employees e
                JOIN offices o
                ON e.officeCode = o.officeCode
                WHERE city = 'Boston';""")
df = pd.DataFrame(cur.fetchall()) #Take results and create dataframe
df.columns = [i[0] for i in cur.description]
df.head()

  firstName   lastName    city
0     Julie   Firrelli  Boston
1     Steve  Patterson  Boston

## Do any offices have no employees?

In [4]:
cur.execute("""select firstName, lastName , city from products p
                JOIN offices o
                ON e.officeCode = o.officeCode
                WHERE city IS NULL;""").fetchall()
# df = pd.DataFrame(cur.fetchall()) #Take results and create dataframe
# df.columns = [i[0] for i in cur.description]
# df.head()

OperationalError: no such column: firstName

## Write 3 Questions of your own and answer them

In [5]:
# Answers will vary

In [6]:
# Your code here

In [7]:
# Your code here

In [8]:
# Your code here

## Level Up: Display the names of each product each employee has sold.

In [16]:
cur.execute("""select productName from products p
                JOIN orderdetails od
                ON p.productcode = od.productcode
                JOIN orders o
                ON od.orderNumber = o.orderNumber
                JOIN customers c
                ON o.customerNumber = c.customerNumber
                JOIN employees e
                ON c.salesRepEmployeeNumber = e.employeeNumber
                ORDER BY lastName;""").fetchall()
# df = pd.DataFrame(cur.fetchall()) #Take results and create dataframe
# df.columns = [i[0] for i in cur.description]
# df.head()

[('1969 Harley Davidson Ultimate Chopper',),
 ('1969 Harley Davidson Ultimate Chopper',),
 ('1969 Harley Davidson Ultimate Chopper',),
 ('1952 Alpine Renault 1300',),
 ('1996 Moto Guzzi 1100i',),
 ('1996 Moto Guzzi 1100i',),
 ('2003 Harley-Davidson Eagle Drag Bike',),
 ('1972 Alfa Romeo GTA',),
 ('1972 Alfa Romeo GTA',),
 ('1962 LanciaA Delta 16V',),
 ('1962 LanciaA Delta 16V',),
 ('1968 Ford Mustang',),
 ('1968 Ford Mustang',),
 ('2001 Ferrari Enzo',),
 ('2001 Ferrari Enzo',),
 ('2001 Ferrari Enzo',),
 ('2001 Ferrari Enzo',),
 ('1958 Setra Bus',),
 ('2002 Suzuki XREO',),
 ('2002 Suzuki XREO',),
 ('2002 Suzuki XREO',),
 ('1969 Corvair Monza',),
 ('1969 Corvair Monza',),
 ('1968 Dodge Charger',),
 ('1969 Ford Falcon',),
 ('1969 Ford Falcon',),
 ('1969 Ford Falcon',),
 ('1970 Plymouth Hemi Cuda',),
 ('1970 Plymouth Hemi Cuda',),
 ('1957 Chevy Pickup',),
 ('1969 Dodge Charger',),
 ('1940 Ford Pickup Truck',),
 ('1993 Mazda RX-7',),
 ('1993 Mazda RX-7',),
 ('1937 Lincoln Berline',),
 ('1937 Lincoln Berline',),
 ('1936 Mercedes-Benz 500K Special Roadster',),
 ('1936 Mercedes-Benz 500K Special Roadster',),
 ('1965 Aston Martin DB5',),
 ('1965 Aston Martin DB5',),
 ('1980s Black Hawk Helicopter',),
 ('1917 Grand Touring Sedan',),
 ('1917 Grand Touring Sedan',),
 ('1948 Porsche 356-A Roadster',),
 ('1995 Honda Civic',),
 ('1995 Honda Civic',),
 ('1998 Chrysler Plymouth Prowler',),
 ('1911 Ford Town Car',),
 ('1911 Ford Town Car',),
 ('1964 Mercedes Tour Bus',),
 ('1932 Model A Ford J-Coupe',),
 ('1932 Model A Ford J-Coupe',),
 ('1932 Model A Ford J-Coupe',),
 ('1926 Ford Fire Engine',),
 ('1926 Ford Fire Engine',),
 ('P-51-D Mustang',),
 ('1936 Harley Davidson El Knucklehead',),
 ('1936 Harley Davidson El Knucklehead',),
 ('1928 Mercedes-Benz SSK',),
 ('1928 Mercedes-Benz SSK',),
 ('1999 Indy 500 Monte Carlo SS',),
 ('1999 Indy 500 Monte Carlo SS',),
 ('1999 Yamaha Speed Boat',),
 ('1903 Ford Model A',),
 ('1903 Ford Model A',),
 ('1992 Ferrari 360 Spider red',),
 ('1992 Ferrari 360 Spider red',),
 ('Collectable Wooden Train',),
 ('Collectable Wooden Train',),
 ('1969 Dodge Super Bee',),
 ('1969 Dodge Super Bee',),
 ('1969 Dodge Super Bee',),
 ('1917 Maxwell Touring Car',),
 ('1976 Ford Gran Torino',),
 ('1976 Ford Gran Torino',),
 ('1976 Ford Gran Torino',),
 ('1948 Porsche Type 356 Roadster',),
 ('1948 Porsche Type 356 Roadster',),
 ('1957 Vespa GS150',),
 ('1957 Vespa GS150',),
 ('1957 Vespa GS150',),
 ('1957 Vespa GS150',),
 ('1941 Chevrolet Special Deluxe Cabriolet',),
 ('1932 Alfa Romeo 8C2300 Spider Sport',),
 ('1932 Alfa Romeo 8C2300 Spider Sport',),
 ('1904 Buick Runabout',),
 ('1940s Ford truck',),
 ('1940s Ford truck',),
 ('1939 Cadillac Limousine',),
 ('1957 Corvette Convertible',),
 ('1957 Corvette Convertible',),
 ('1957 Corvette Convertible',),
 ('1957 Ford Thunderbird',),
 ('1957 Ford Thunderbird',),
 ('1970 Chevy Chevelle SS 454',),
 ('1970 Dodge Coronet',),
 ('1997 BMW R 1100 S',),
 ('1997 BMW R 1100 S',),
 ('1966 Shelby Cobra 427 S/C',),
 ('1966 Shelby Cobra 427 S/C',),
 ('1928 British Royal Navy Airplane',),
 ('1939 Chevrolet Deluxe Coupe',),
 ('1939 Chevrolet Deluxe Coupe',),
 ('1939 Chevrolet Deluxe Coupe',),
 ('1960 BSA Gold Star DBD34',),
 ('1960 BSA Gold Star DBD34',),
 ('18th century schooner',),
 ('1938 Cadillac V-16 Presidential Limousine',),
 ('1938 Cadillac V-16 Presidential Limousine',),
 ('1962 Volkswagen Microbus',),
 ('1962 Volkswagen Microbus',),
 ('1982 Ducati 900 Monster',),
 ('1982 Ducati 900 Monster',),
 ('1982 Ducati 900 Monster',),
 ('1949 Jaguar XK 120',),
 ('1958 Chevy Corvette Limited Edition',),
 ('1900s Vintage Bi-Plane',),
 ('1952 Citroen-15CV',),
 ('1982 Lamborghini Diablo',),
 ('1912 Ford Model T Delivery Wagon',),
 ('1969 Chevrolet Camaro Z28',),
 ('1971 Alpine Renault 1600s',),
 ('1971 Alpine Renault 1600s',),
 ('1937 Horch 930V Limousine',),
 ('1956 Porsche 356A Coupe',),
 ('Corsair F4U ( Bird Cage)',),
 ('1936 Mercedes Benz 500k Roadster',),
 ('1992 Porsche Cayenne Turbo Silver',),
 ('1992 Porsche Cayenne Turbo Silver',),
 ('1900s Vintage Tri-Plane',),
 ('1961 Chevrolet Impala',),
 ('1961 Chevrolet Impala',),
 ('1961 Chevrolet Impala',),
 ('1961 Chevrolet Impala',),
 ('1980’s GM Manhattan Express',),
 ('1980’s GM Manhattan Express',),
 ('1982 Ducati 996 R',),
 ('1982 Ducati 996 R',),
 ('1982 Ducati 996 R',),
 ('1982 Ducati 996 R',),
 ('1982 Ducati 996 R',),
 ('1954 Greyhound Scenicruiser',),
 ('1954 Greyhound Scenicruiser',),
 ("1950's Chicago Surface Lines Streetcar",),
 ("1950's Chicago Surface Lines Streetcar",),
 ('1996 Peterbilt 379 Stake Bed with Outrigger',),
 ('1928 Ford Phaeton Deluxe',),
 ('1974 Ducati 350 Mk3 Desmo',),
 ('1974 Ducati 350 Mk3 Desmo',),
 ('1974 Ducati 350 Mk3 Desmo',),
 ('1930 Buick Marquette Phaeton',),
 ('Diamond T620 Semi-Skirted Tanker',),
 ('Diamond T620 Semi-Skirted Tanker',),
 ('Diamond T620 Semi-Skirted Tanker',),
 ('1962 City of Detroit Streetcar',),
 ('1962 City of Detroit Streetcar',),
 ('1962 City of Detroit Streetcar',),
 ('2002 Yamaha YZR M1',),
 ('2002 Yamaha YZR M1',),
 ('2002 Yamaha YZR M1',),
 ('2002 Yamaha YZR M1',),
 ('The Schooner Bluenose',),
 ('American Airlines: B767-300',),
 ('The Mayflower',),
 ('HMS Bounty',),
 ('America West Airlines B757-200',),
 ('The USS Constitution Ship',),
 ('1982 Camaro Z28',),
 ('1982 Camaro Z28',),
 ('1982 Camaro Z28',),
 ('ATA: B757-300',),
 ('F/A 18 Hornet 1/72',),
 ('The Titanic',),
 ('The Queen Mary',),
 ('American Airlines: MD-11S',),
 ('Boeing X-32A JSF',),
 ('Pont Yacht',),
 ('1969 Harley Davidson Ultimate Chopper',),
 ('1969 Harley Davidson Ultimate Chopper',),
 ('2003 Harley-Davidson Eagle Drag Bike',),
 ('2003 Harley-Davidson Eagle Drag Bike',),
 ('1972 Alfa Romeo GTA',),
 ('1972 Alfa Romeo GTA',),
 ('1972 Alfa Romeo GTA',),
 ('1972 Alfa Romeo GTA',),
 ('1972 Alfa Romeo GTA',),
 ('1962 LanciaA Delta 16V',),
 ('1968 Ford Mustang',),
 ('1968 Ford Mustang',),
 ('2001 Ferrari Enzo',),
 ('2001 Ferrari Enzo',),
 ('2002 Suzuki XREO',),
 ('2002 Suzuki XREO',),
 ('1969 Corvair Monza',),
 ('1969 Corvair Monza',),
 ('1968 Dodge Charger',),
 ('1968 Dodge Charger',),
 ('1969 Ford Falcon',),
 ('1969 Ford Falcon',),
 ('1970 Plymouth Hemi Cuda',),
 ('1970 Plymouth Hemi Cuda',),
 ('1970 Plymouth Hemi Cuda',),
 ('1957 Chevy Pickup',),
 ('1957 Chevy Pickup',),
 ('1957 Chevy Pickup',),
 ('1969 Dodge Charger',),
 ('1969 Dodge Charger',),
 ('1969 Dodge Charger',),
 ('1969 Dodge Charger',),
 ('1993 Mazda RX-7',),
 ('1993 Mazda RX-7',),
 ('1937 Lincoln Berline',),
 ('1936 Mercedes-Benz 500K Special Roadster',),
 ('1965 Aston Martin DB5',),
 ('1965 Aston Martin DB5',),
 ('1980s Black Hawk Helicopter',),
 ('1980s Black Hawk Helicopter',),
 ('1980s Black Hawk Helicopter',),
 ('1980s Black Hawk Helicopter',),
 ('1980s Black Hawk Helicopter',),
 ('1917 Grand Touring Sedan',),
 ('1917 Grand Touring Sedan',),
 ('1948 Porsche 356-A Roadster',),
 ('1948 Porsche 356-A Roadster',),
 ('1948 Porsche 356-A Roadster',),
 ('1948 Porsche 356-A Roadster',),
 ('1995 Honda Civic',),
 ('1995 Honda Civic',),
 ('1998 Chrysler Plymouth Prowler',),
 ('1998 Chrysler Plymouth Prowler',),
 ('1911 Ford Town Car',),
 ('1911 Ford Town Car',),
 ('1964 Mercedes Tour Bus',),
 ('1964 Mercedes Tour Bus',),
 ('1964 Mercedes Tour Bus',),
 ('1932 Model A Ford J-Coupe',),
 ('1932 Model A Ford J-Coupe',),
 ('1926 Ford Fire Engine',),
 ('1926 Ford Fire Engine',),
 ('1928 Mercedes-Benz SSK',),
 ('1928 Mercedes-Benz SSK',),
 ('1999 Indy 500 Monte Carlo SS',),
 ('1934 Ford V8 Coupe',),
 ('1999 Yamaha Speed Boat',),
 ('1999 Yamaha Speed Boat',),
 ('1999 Yamaha Speed Boat',),
 ('1999 Yamaha Speed Boat',),
 ('18th Century Vintage Horse Carriage',),
 ('1903 Ford Model A',),
 ('1903 Ford Model A',),
 ('1992 Ferrari 360 Spider red',),
 ('1992 Ferrari 360 Spider red',),
 ('1992 Ferrari 360 Spider red',),
 ('1992 Ferrari 360 Spider red',),
 ('1992 Ferrari 360 Spider red',),
 ('1992 Ferrari 360 Spider red',),
 ('Collectable Wooden Train',),
 ('Collectable Wooden Train',),
 ('1969 Dodge Super Bee',),
 ('1976 Ford Gran Torino',),
 ('1948 Porsche Type 356 Roadster',),
 ('1957 Vespa GS150',),
 ('1957 Vespa GS150',),
 ('1957 Vespa GS150',),
 ('1941 Chevrolet Special Deluxe Cabriolet',),
 ('1941 Chevrolet Special Deluxe Cabriolet',),
 ('1941 Chevrolet Special Deluxe Cabriolet',),
 ('1941 Chevrolet Special Deluxe Cabriolet',),
 ('1941 Chevrolet Special Deluxe Cabriolet',),
 ('1970 Triumph Spitfire',),
 ('1970 Triumph Spitfire',),
 ('1932 Alfa Romeo 8C2300 Spider Sport',),
 ('1932 Alfa Romeo 8C2300 Spider Sport',),
 ('1932 Alfa Romeo 8C2300 Spider Sport',),
 ('1932 Alfa Romeo 8C2300 Spider Sport',),
 ('1904 Buick Runabout',),
 ('1904 Buick Runabout',),
 ('1940s Ford truck',),
 ('1957 Corvette Convertible',),
 ('1957 Corvette Convertible',),
 ('1957 Ford Thunderbird',),
 ('1957 Ford Thunderbird',),
 ('1957 Ford Thunderbird',),
 ('1957 Ford Thunderbird',),
 ('1970 Chevy Chevelle SS 454',),
 ('1970 Chevy Chevelle SS 454',),
 ('1970 Dodge Coronet',),
 ('1997 BMW R 1100 S',),
 ('1997 BMW R 1100 S',),
 ('1966 Shelby Cobra 427 S/C',),
 ('1966 Shelby Cobra 427 S/C',),
 ('1928 British Royal Navy Airplane',),
 ('1939 Chevrolet Deluxe Coupe',),
 ('1939 Chevrolet Deluxe Coupe',),
 ('1960 BSA Gold Star DBD34',),
 ('18th century schooner',),
 ('18th century schooner',),
 ('18th century schooner',),
 ('1938 Cadillac V-16 Presidential Limousine',),
 ('1938 Cadillac V-16 Presidential Limousine',),
 ('1962 Volkswagen Microbus',),
 ('1962 Volkswagen Microbus',),
 ('1982 Ducati 900 Monster',),
 ('1982 Ducati 900 Monster',),
 ('1982 Ducati 900 Monster',),
 ('1949 Jaguar XK 120',),
 ('1949 Jaguar XK 120',),
 ('1949 Jaguar XK 120',),
 ('1958 Chevy Corvette Limited Edition',),
 ('1958 Chevy Corvette Limited Edition',),
 ('1958 Chevy Corvette Limited Edition',),
 ('1900s Vintage Bi-Plane',),
 ('1900s Vintage Bi-Plane',),
 ('1900s Vintage Bi-Plane',),
 ('1900s Vintage Bi-Plane',),
 ('1900s Vintage Bi-Plane',),
 ('1952 Citroen-15CV',),
 ('1952 Citroen-15CV',),
 ('1952 Citroen-15CV',),
 ('1952 Citroen-15CV',),
 ('1982 Lamborghini Diablo',),
 ('1982 Lamborghini Diablo',),
 ('1912 Ford Model T Delivery Wagon',),
 ('1912 Ford Model T Delivery Wagon',),
 ('1912 Ford Model T Delivery Wagon',),
 ('1969 Chevrolet Camaro Z28',),
 ('1969 Chevrolet Camaro Z28',),
 ('1969 Chevrolet Camaro Z28',),
 ('1971 Alpine Renault 1600s',),
 ('1971 Alpine Renault 1600s',),
 ('1937 Horch 930V Limousine',),
 ('1937 Horch 930V Limousine',),
 ('1937 Horch 930V Limousine',),
 ('1937 Horch 930V Limousine',),
 ('1937 Horch 930V Limousine',),
 ('2002 Chevy Corvette',),
 ('2002 Chevy Corvette',),
 ('1940 Ford Delivery Sedan',),
 ('1940 Ford Delivery Sedan',),
 ('1940 Ford Delivery Sedan',),
 ('1940 Ford Delivery Sedan',),
 ('1940 Ford Delivery Sedan',),
 ('1956 Porsche 356A Coupe',),
 ('1956 Porsche 356A Coupe',),
 ('1956 Porsche 356A Coupe',),
 ('Corsair F4U ( Bird Cage)',),
 ('Corsair F4U ( Bird Cage)',),
 ('Corsair F4U ( Bird Cage)',),
 ('Corsair F4U ( Bird Cage)',),
 ('1936 Mercedes Benz 500k Roadster',),
 ('1936 Mercedes Benz 500k Roadster',),
 ('1992 Porsche Cayenne Turbo Silver',),
 ('1961 Chevrolet Impala',),
 ('1961 Chevrolet Impala',),
 ('1980’s GM Manhattan Express',),
 ('1980’s GM Manhattan Express',),
 ('1997 BMW F650 ST',),
 ('1982 Ducati 996 R',),
 ('1982 Ducati 996 R',),
 ('1954 Greyhound Scenicruiser',),
 ('1954 Greyhound Scenicruiser',),
 ('1954 Greyhound Scenicruiser',),
 ("1950's Chicago Surface Lines Streetcar",),
 ("1950's Chicago Surface Lines Streetcar",),
 ('1996 Peterbilt 379 Stake Bed with Outrigger',),
 ('1928 Ford Phaeton Deluxe',),
 ('1974 Ducati 350 Mk3 Desmo',),
 ('1974 Ducati 350 Mk3 Desmo',),
 ('1930 Buick Marquette Phaeton',),
 ('Diamond T620 Semi-Skirted Tanker',),
 ('Diamond T620 Semi-Skirted Tanker',),
 ('1962 City of Detroit Streetcar',),
 ('1962 City of Detroit Streetcar',),
 ('2002 Yamaha YZR M1',),
 ('2002 Yamaha YZR M1',),
 ('The Schooner Bluenose',),
 ('The Schooner Bluenose',),
 ('The Schooner Bluenose',),
 ('American Airlines: B767-300',),
 ('The Mayflower',),
 ('The Mayflower',),
 ('HMS Bounty',),
 ('HMS Bounty',),
 ('HMS Bounty',),
 ('HMS Bounty',),
 ('America West Airlines B757-200',),
 ('America West Airlines B757-200',),
 ('The USS Constitution Ship',),
 ('The USS Constitution Ship',),
 ('The USS Constitution Ship',),
 ('The USS Constitution Ship',),
 ('1982 Camaro Z28',),
 ('F/A 18 Hornet 1/72',),
 ('F/A 18 Hornet 1/72',),
 ('The Titanic',),
 ('The Titanic',),
 ('The Titanic',),
 ('The Titanic',),
 ('The Queen Mary',),
 ('The Queen Mary',),
 ('The Queen Mary',),
 ('The Queen Mary',),
 ('American Airlines: MD-11S',),
 ('American Airlines: MD-11S',),
 ('American Airlines: MD-11S',),
 ('Boeing X-32A JSF',),
 ('Boeing X-32A JSF',),
 ('Boeing X-32A JSF',),
 ('Boeing X-32A JSF',),
 ('Pont Yacht',),
 ('Pont Yacht',),
 ('Pont Yacht',),
 ('Pont Yacht',),
 ('1969 Harley Davidson Ultimate Chopper',),
 ('1952 Alpine Renault 1300',),
 ('1972 Alfa Romeo GTA',),
 ('1972 Alfa Romeo GTA',),
 ('1972 Alfa Romeo GTA',),
 ('1962 LanciaA Delta 16V',),
 ('1968 Ford Mustang',),
 ('1968 Ford Mustang',),
 ('1968 Ford Mustang',),
 ('1968 Ford Mustang',),
 ('2001 Ferrari Enzo',),
 ('2001 Ferrari Enzo',),
 ('2001 Ferrari Enzo',),
 ('2001 Ferrari Enzo',),
 ('1958 Setra Bus',),
 ('2002 Suzuki XREO',),
 ('1969 Corvair Monza',),
 ('1969 Corvair Monza',),
 ('1969 Corvair Monza',),
 ('1968 Dodge Charger',),
 ('1968 Dodge Charger',),
 ('1968 Dodge Charger',),
 ('1968 Dodge Charger',),
 ('1968 Dodge Charger',),
 ('1969 Ford Falcon',),
 ('1969 Ford Falcon',),
 ('1969 Ford Falcon',),
 ('1969 Ford Falcon',),
 ('1970 Plymouth Hemi Cuda',),
 ('1970 Plymouth Hemi Cuda',),
 ('1970 Plymouth Hemi Cuda',),
 ('1970 Plymouth Hemi Cuda',),
 ('1957 Chevy Pickup',),
 ('1969 Dodge Charger',),
 ('1969 Dodge Charger',),
 ('1969 Dodge Charger',),
 ('1969 Dodge Charger',),
 ('1940 Ford Pickup Truck',),
 ('1940 Ford Pickup Truck',),
 ('1993 Mazda RX-7',),
 ('1993 Mazda RX-7',),
 ('1993 Mazda RX-7',),
 ('1993 Mazda RX-7',),
 ('1937 Lincoln Berline',),
 ('1937 Lincoln Berline',),
 ('1937 Lincoln Berline',),
 ('1936 Mercedes-Benz 500K Special Roadster',),
 ('1936 Mercedes-Benz 500K Special Roadster',),
 ('1936 Mercedes-Benz 500K Special Roadster',),
 ('1965 Aston Martin DB5',),
 ('1965 Aston Martin DB5',),
 ('1965 Aston Martin DB5',),
 ('1980s Black Hawk Helicopter',),
 ('1980s Black Hawk Helicopter',),
 ('1980s Black Hawk Helicopter',),
 ('1980s Black Hawk Helicopter',),
 ('1980s Black Hawk Helicopter',),
 ('1917 Grand Touring Sedan',),
 ('1917 Grand Touring Sedan',),
 ('1948 Porsche 356-A Roadster',),
 ('1948 Porsche 356-A Roadster',),
 ('1948 Porsche 356-A Roadster',),
 ('1995 Honda Civic',),
 ('1995 Honda Civic',),
 ('1995 Honda Civic',),
 ('1995 Honda Civic',),
 ('1995 Honda Civic',),
 ('1998 Chrysler Plymouth Prowler',),
 ('1998 Chrysler Plymouth Prowler',),
 ('1911 Ford Town Car',),
 ('1911 Ford Town Car',),
 ('1964 Mercedes Tour Bus',),
 ('1932 Model A Ford J-Coupe',),
 ('1932 Model A Ford J-Coupe',),
 ('P-51-D Mustang',),
 ('P-51-D Mustang',),
 ('P-51-D Mustang',),
 ('P-51-D Mustang',),
 ('1928 Mercedes-Benz SSK',),
 ('1928 Mercedes-Benz SSK',),
 ('1999 Indy 500 Monte Carlo SS',),
 ('1999 Indy 500 Monte Carlo SS',),
 ('1999 Indy 500 Monte Carlo SS',),
 ('1999 Indy 500 Monte Carlo SS',),
 ('1913 Ford Model T Speedster',),
 ('1913 Ford Model T Speedster',),
 ('1934 Ford V8 Coupe',),
 ('1934 Ford V8 Coupe',),
 ('1934 Ford V8 Coupe',),
 ('1934 Ford V8 Coupe',),
 ('1934 Ford V8 Coupe',),
 ('1999 Yamaha Speed Boat',),
 ('1999 Yamaha Speed Boat',),
 ('1999 Yamaha Speed Boat',),
 ('1999 Yamaha Speed Boat',),
 ('1999 Yamaha Speed Boat',),
 ('18th Century Vintage Horse Carriage',),
 ('18th Century Vintage Horse Carriage',),
 ('18th Century Vintage Horse Carriage',),
 ('18th Century Vintage Horse Carriage',),
 ('1903 Ford Model A',),
 ('1903 Ford Model A',),
 ('1903 Ford Model A',),
 ('1903 Ford Model A',),
 ('1903 Ford Model A',),
 ('1992 Ferrari 360 Spider red',),
 ('1992 Ferrari 360 Spider red',),
 ('1992 Ferrari 360 Spider red',),
 ('1992 Ferrari 360 Spider red',),
 ('Collectable Wooden Train',),
 ('Collectable Wooden Train',),
 ('Collectable Wooden Train',),
 ('Collectable Wooden Train',),
 ('Collectable Wooden Train',),
 ('1969 Dodge Super Bee',),
 ('1917 Maxwell Touring Car',),
 ('1917 Maxwell Touring Car',),
 ('1917 Maxwell Touring Car',),
 ('1917 Maxwell Touring Car',),
 ('1976 Ford Gran Torino',),
 ('1948 Porsche Type 356 Roadster',),
 ('1948 Porsche Type 356 Roadster',),
 ('1948 Porsche Type 356 Roadster',),
 ('1948 Porsche Type 356 Roadster',),
 ('1941 Chevrolet Special Deluxe Cabriolet',),
 ('1941 Chevrolet Special Deluxe Cabriolet',),
 ('1941 Chevrolet Special Deluxe Cabriolet',),
 ('1941 Chevrolet Special Deluxe Cabriolet',),
 ('1941 Chevrolet Special Deluxe Cabriolet',),
 ('1970 Triumph Spitfire',),
 ('1970 Triumph Spitfire',),
 ('1932 Alfa Romeo 8C2300 Spider Sport',),
 ('1932 Alfa Romeo 8C2300 Spider Sport',),
 ('1904 Buick Runabout',),
 ('1904 Buick Runabout',),
 ('1904 Buick Runabout',),
 ('1904 Buick Runabout',),
 ('1940s Ford truck',),
 ('1939 Cadillac Limousine',),
 ('1957 Corvette Convertible',),
 ('1957 Ford Thunderbird',),
 ('1957 Ford Thunderbird',),
 ('1970 Chevy Chevelle SS 454',),
 ('1970 Dodge Coronet',),
 ('1970 Dodge Coronet',),
 ('1966 Shelby Cobra 427 S/C',),
 ('1966 Shelby Cobra 427 S/C',),
 ('1928 British Royal Navy Airplane',),
 ('1928 British Royal Navy Airplane',),
 ('1928 British Royal Navy Airplane',),
 ('1928 British Royal Navy Airplane',),
 ('1939 Chevrolet Deluxe Coupe',),
 ('1939 Chevrolet Deluxe Coupe',),
 ('1960 BSA Gold Star DBD34',),
 ('18th century schooner',),
 ('18th century schooner',),
 ('18th century schooner',),
 ('18th century schooner',),
 ('1938 Cadillac V-16 Presidential Limousine',),
 ('1938 Cadillac V-16 Presidential Limousine',),
 ('1982 Ducati 900 Monster',),
 ('1949 Jaguar XK 120',),
 ('1958 Chevy Corvette Limited Edition',),
 ('1900s Vintage Bi-Plane',),
 ('1900s Vintage Bi-Plane',),
 ('1900s Vintage Bi-Plane',),
 ('1952 Citroen-15CV',),
 ('1952 Citroen-15CV',),
 ('1982 Lamborghini Diablo',),
 ('1982 Lamborghini Diablo',),
 ('1912 Ford Model T Delivery Wagon',),
 ('1912 Ford Model T Delivery Wagon',),
 ('1912 Ford Model T Delivery Wagon',),
 ('1969 Chevrolet Camaro Z28',),
 ('1971 Alpine Renault 1600s',),
 ('1971 Alpine Renault 1600s',),
 ('1971 Alpine Renault 1600s',),
 ('1937 Horch 930V Limousine',),
 ('1937 Horch 930V Limousine',),
 ('1937 Horch 930V Limousine',),
 ('2002 Chevy Corvette',),
 ('1940 Ford Delivery Sedan',),
 ('1940 Ford Delivery Sedan',),
 ('1940 Ford Delivery Sedan',),
 ('1956 Porsche 356A Coupe',),
 ('1956 Porsche 356A Coupe',),
 ('1956 Porsche 356A Coupe',),
 ('Corsair F4U ( Bird Cage)',),
 ('Corsair F4U ( Bird Cage)',),
 ('Corsair F4U ( Bird Cage)',),
 ('Corsair F4U ( Bird Cage)',),
 ('1936 Mercedes Benz 500k Roadster',),
 ('1936 Mercedes Benz 500k Roadster',),
 ('1992 Porsche Cayenne Turbo Silver',),
 ('1992 Porsche Cayenne Turbo Silver',),
 ('1936 Chrysler Airflow',),
 ('1936 Chrysler Airflow',),
 ('1936 Chrysler Airflow',),
 ('1936 Chrysler Airflow',),
 ('1900s Vintage Tri-Plane',),
 ('1900s Vintage Tri-Plane',),
 ('1900s Vintage Tri-Plane',),
 ('1900s Vintage Tri-Plane',),
 ('1961 Chevrolet Impala',),
 ('1980’s GM Manhattan Express',),
 ('1997 BMW F650 ST',),
 ('1997 BMW F650 ST',),
 ("1950's Chicago Surface Lines Streetcar",),
 ("1950's Chicago Surface Lines Streetcar",),
 ("1950's Chicago Surface Lines Streetcar",),
 ('1996 Peterbilt 379 Stake Bed with Outrigger',),
 ('1928 Ford Phaeton Deluxe',),
 ('1928 Ford Phaeton Deluxe',),
 ('1928 Ford Phaeton Deluxe',),
 ('1928 Ford Phaeton Deluxe',),
 ('1928 Ford Phaeton Deluxe',),
 ('1974 Ducati 350 Mk3 Desmo',),
 ('1930 Buick Marquette Phaeton',),
 ('1930 Buick Marquette Phaeton',),
 ('1930 Buick Marquette Phaeton',),
 ('Diamond T620 Semi-Skirted Tanker',),
 ('Diamond T620 Semi-Skirted Tanker',),
 ('1962 City of Detroit Streetcar',),
 ('1962 City of Detroit Streetcar',),
 ('2002 Yamaha YZR M1',),

## Level Up: Display the Number of Products each Employee Has sold

In [17]:
cur.execute("""SELECT lastName, firstName, COUNT(productName) as sum_products FROM products p
                JOIN orderdetails od
                ON p.productcode = od.productcode
                JOIN orders o
                ON od.orderNumber = o.orderNumber
                JOIN customers c
                ON o.customerNumber = c.customerNumber
                JOIN employees e
                ON c.salesRepEmployeeNumber = e.employeeNumber
                GROUP BY lastName
                ORDER BY sum_products DESC;""").fetchall()
                
# df = pd.DataFrame(cur.fetchall()) #Take results and create dataframe
# df.columns = [i[0] for i in cur.description]
# df.head()

[('Hernandez', 'Gerard', 396),
 ('Jennings', 'Leslie', 331),
 ('Castillo', 'Pamela', 272),
 ('Bott', 'Larry', 236),
 ('Jones', 'Barry', 220),
 ('Vanauf', 'George', 211),
 ('Fixter', 'Andy', 185),
 ('Marsh', 'Peter', 185),
 ('Bondur', 'Loui', 177),
 ('Patterson', 'Steve', 152),
 ('Tseng', 'Foon Yue', 142),
 ('Nishi', 'Mami', 137),
 ('Firrelli', 'Julie', 124),
 ('Gerard', 'Martin', 114),
 ('Thompson', 'Leslie', 114)]

## Summary

Congrats! You now know how to use Join statements, along with leveraging your foreign keys knowledge!